import { buildShopeeSearchTerms, type ProductIntelligenceSeed } from "./intelligence";

type PublicCompetitor={title:string;url:string;price:number|null;shopId:number;itemId:number;categoryId:string|null;category:string|null;attributes:Record<string,string>};
export type ShopeePublicResearch={competitors:PublicCompetitor[];priceMin:number|null;priceMedian:number|null;priceMax:number|null;category:string|null;categoryId:string|null;attributes:Record<string,string>;searchTerms:string[];source:string};
const headers={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","accept":"application/json,text/plain,*/*","accept-language":"pt-BR,pt;q=0.9,en;q=0.8","referer":"https://shopee.com.br/","x-api-source":"pc"};
const htmlHeaders={...headers,accept:"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"};
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const words=(v:string)=>new Set(normalize(v).split(/[^a-z0-9]+/).filter(x=>x.length>2));
const overlap=(target:Set<string>,candidate:string)=>{const c=words(candidate);let hits=0;target.forEach(w=>{if(c.has(w))hits++});return target.size?hits/target.size:0};
const money=(v:unknown)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)return null;return n>100000?n/100000:n};
async function request(url:string,acceptHeaders:Record<string,string>=headers){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{return await fetch(url,{headers:acceptHeaders,cache:"no-store",signal:controller.signal,redirect:"follow"})}finally{clearTimeout(timer)}}
async function json(url:string){const r=await request(url);if(!r.ok)throw new Error(`Shopee HTTP ${r.status}`);return await r.json()}
function itemBasic(row:any){return row?.item_basic??row?.item??row??{}}
async function detail(shopId:number,itemId:number){try{const data=await json(`https://shopee.com.br/api/v4/pdp/get_pc?item_id=${itemId}&shop_id=${shopId}`);const item=data?.data?.item??data?.data??{};const cats=item?.categories??item?.category_path??[];const last=Array.isArray(cats)&&cats.length?cats[cats.length-1]:null;const attrs:Record<string,string>={};for(const a of item?.attributes??[]){const name=String(a?.name??a?.display_name??"").trim();const value=String(a?.value??a?.display_value??a?.values?.map((x:any)=>x?.name??x?.value).filter(Boolean).join(", ")??"").trim();if(name&&value)attrs[name]=value}return{categoryId:last?.catid!=null?String(last.catid):item?.catid!=null?String(item.catid):null,category:String(last?.display_name??last?.name??item?.category_name??"").trim()||null,attributes:attrs}}catch{return{categoryId:null,category:null,attributes:{}}}}
async function searchApi(query:string){const common=`by=relevancy&keyword=${encodeURIComponent(query)}&limit=60&newest=0&order=desc&page_type=search&scenario=PAGE_GLOBAL_SEARCH&version=2`;for(const url of [`https://shopee.com.br/api/v4/search/search_items?${common}`,`https://shopee.com.br/api/v4/search/search_items?${common}&view_session_id=wjr-seller`]){try{const data=await json(url);if(Array.isArray(data?.items)&&data.items.length)return data.items}catch{}}return []}
function decodeHtml(s:string){return s.replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/\\u002F/g,'/').replace(/\\u0026/g,'&').replace(/\\u003C/g,'<').replace(/\\u003E/g,'>')}
function extractJsonObjects(html:string){const rows:any[]=[];const decoded=decodeHtml(html);const patterns=[/\{[^{}]{0,1800}"itemid"\s*:\s*(\d+)[^{}]{0,1800}"shopid"\s*:\s*(\d+)[^{}]{0,3500}\}/g,/\{[^{}]{0,1800}"shopid"\s*:\s*(\d+)[^{}]{0,1800}"itemid"\s*:\s*(\d+)[^{}]{0,3500}\}/g];for(const re of patterns){for(const m of decoded.matchAll(re)){try{const obj=JSON.parse(m[0]);if(obj?.itemid&&obj?.shopid)rows.push(obj)}catch{const text=m[0];const itemid=Number(text.match(/"itemid"\s*:\s*(\d+)/)?.[1]);const shopid=Number(text.match(/"shopid"\s*:\s*(\d+)/)?.[1]);const name=text.match(/"name"\s*:\s*"((?:\\.|[^"\\])*)"/)?.[1];const price=Number(text.match(/"price(?:_min)?"\s*:\s*(\d+)/)?.[1]);if(itemid&&shopid&&name)rows.push({itemid,shopid,name:name.replace(/\\"/g,'"'),price})}}}return rows}
async function searchHtml(query:string){try{const r=await request(`https://shopee.com.br/search?keyword=${encodeURIComponent(query)}`,htmlHeaders);if(!r.ok)return [];const html=await r.text();const rows=extractJsonObjects(html);if(rows.length)return rows;const decoded=decodeHtml(html);const links=[...decoded.matchAll(/href=["']([^"']*(?:-i\.(\d+)\.(\d+)|\/product\/(\d+)\/(\d+))[^"']*)["']/g)];return links.map(m=>{const shopid=Number(m[2]??m[4]);const itemid=Number(m[3]??m[5]);const pos=m.index??0;const chunk=decoded.slice(Math.max(0,pos-1600),Math.min(decoded.length,pos+1600));const title=chunk.match(/(?:title|name)=["']([^"']{8,220})["']/i)?.[1]??chunk.match(/"name"\s*:\s*"([^"]{8,220})"/)?.[1]??"";const brl=chunk.match(/R\$\s*([0-9.]+,[0-9]{2})/);const price=brl?Number(brl[1].replace(/\./g,'').replace(',','.')):null;return{shopid,itemid,name:title,price}}).filter(x=>x.shopid&&x.itemid&&x.name)}catch{return []}}
async function search(query:string){const api=await searchApi(query);if(api.length)return{rows:api,source:"shopee_public_api"};const html=await searchHtml(query);return{rows:html,source:html.length?"shopee_public_html":"shopee_public_unavailable"}}
export async function researchShopeePublic(seed:ProductIntelligenceSeed):Promise<ShopeePublicResearch|null>{const searchTerms=buildShopeeSearchTerms(seed);const queries=Array.from(new Set([[seed.name,seed.brand,seed.model].filter(Boolean).join(" ").trim(),seed.name,searchTerms.slice(0,6).join(" ")].filter(Boolean))) as string[];if(!queries.length)return null;try{const rows:any[]=[];let source="shopee_public_unavailable";for(const q of queries){const found=await search(q);if(found.source!=="shopee_public_unavailable")source=found.source;rows.push(...found.rows);if(rows.length>=60)break}const target=words([seed.name,seed.brand,seed.model].filter(Boolean).join(" "));const seen=new Set<string>();const candidates=rows.map(itemBasic).map((i:any)=>({raw:i,score:overlap(target,String(i?.name??""))})).filter((x:any)=>{const key=`${x.raw?.shopid}:${x.raw?.itemid}`;if(!x.raw?.itemid||!x.raw?.shopid||seen.has(key)||x.score<0.3)return false;seen.add(key);return true}).sort((a:any,b:any)=>b.score-a.score).slice(0,12);if(!candidates.length)return null;const competitors:PublicCompetitor[]=[];for(const c of candidates){const i=c.raw,d=await detail(Number(i.shopid),Number(i.itemid));competitors.push({title:String(i.name??""),url:`https://shopee.com.br/product/${i.shopid}/${i.itemid}`,price:money(i.price_min??i.price),shopId:Number(i.shopid),itemId:Number(i.itemid),...d})}const prices=competitors.map(x=>x.price).filter((v):v is number=>v!=null).sort((a,b)=>a-b);const median=prices.length?(prices.length%2?prices[(prices.length-1)/2]:(prices[prices.length/2-1]+prices[prices.length/2])/2):null;const categories=competitors.filter(x=>x.category).reduce((m,x)=>{const k=`${x.categoryId??""}|${x.category}`;m.set(k,(m.get(k)??0)+1);return m},new Map<string,number>());const categoryEntry=[...categories.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0];const [categoryId,category]=categoryEntry?categoryEntry.split("|",2):[null,null];const attrVotes=new Map<string,Map<string,number>>();for(const c of competitors)for(const[k,v]of Object.entries(c.attributes)){if(!attrVotes.has(k))attrVotes.set(k,new Map());const vm=attrVotes.get(k)!;vm.set(v,(vm.get(v)??0)+1)}const attributes:Record<string,string>={};for(const[k,vm]of attrVotes){const best=[...vm.entries()].sort((a,b)=>b[1]-a[1])[0];if(best&&best[1]>=2)attributes[k]=best[0]}return{competitors,priceMin:prices[0]??null,priceMedian:median,priceMax:prices[prices.length-1]??null,category:category||null,categoryId:categoryId||null,attributes,searchTerms,source}}catch{return null}}
