import { buildShopeeSearchTerms, type ProductIntelligenceSeed } from "./intelligence";

type PublicCompetitor={title:string;url:string;price:number|null;shopId:number;itemId:number;categoryId:string|null;category:string|null;attributes:Record<string,string>};
export type ShopeePublicResearch={competitors:PublicCompetitor[];priceMin:number|null;priceMedian:number|null;priceMax:number|null;category:string|null;categoryId:string|null;attributes:Record<string,string>;searchTerms:string[];source:string};
const headers={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36","accept":"application/json,text/plain,*/*","referer":"https://shopee.com.br/"};
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const words=(v:string)=>new Set(normalize(v).split(/[^a-z0-9]+/).filter(x=>x.length>2));
const overlap=(target:Set<string>,candidate:string)=>{const c=words(candidate);let hits=0;target.forEach(w=>{if(c.has(w))hits++});return target.size?hits/target.size:0};
const money=(v:unknown)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)return null;return n>100000?n/100000:n};
async function json(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(url,{headers,cache:"no-store",signal:controller.signal});if(!r.ok)throw new Error(`Shopee HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
function itemBasic(row:any){return row?.item_basic??row?.item??row??{}}
async function detail(shopId:number,itemId:number){try{const data=await json(`https://shopee.com.br/api/v4/pdp/get_pc?item_id=${itemId}&shop_id=${shopId}`);const item=data?.data?.item??data?.data??{};const cats=item?.categories??item?.category_path??[];const last=Array.isArray(cats)&&cats.length?cats[cats.length-1]:null;const attrs:Record<string,string>={};for(const a of item?.attributes??[]){const name=String(a?.name??a?.display_name??"").trim();const value=String(a?.value??a?.display_value??a?.values?.map((x:any)=>x?.name??x?.value).filter(Boolean).join(", ")??"").trim();if(name&&value)attrs[name]=value}return{categoryId:last?.catid!=null?String(last.catid):item?.catid!=null?String(item.catid):null,category:String(last?.display_name??last?.name??item?.category_name??"").trim()||null,attributes:attrs}}catch{return{categoryId:null,category:null,attributes:{}}}}
export async function researchShopeePublic(seed:ProductIntelligenceSeed):Promise<ShopeePublicResearch|null>{const searchTerms=buildShopeeSearchTerms(seed),query=[seed.name,seed.brand,seed.model].filter(Boolean).join(" ").trim();if(!query)return null;try{const data=await json(`https://shopee.com.br/api/v4/search/search_items?by=relevancy&keyword=${encodeURIComponent(query)}&limit=30&newest=0&order=desc&page_type=search&scenario=PAGE_GLOBAL_SEARCH&version=2`);const target=words(query);const candidates=(data?.items??[]).map(itemBasic).map((i:any)=>({raw:i,score:overlap(target,String(i?.name??""))})).filter((x:any)=>x.raw?.itemid&&x.raw?.shopid&&x.score>=0.35).sort((a:any,b:any)=>b.score-a.score).slice(0,6);if(!candidates.length)return null;const competitors:PublicCompetitor[]=[];for(const c of candidates){const i=c.raw,d=await detail(Number(i.shopid),Number(i.itemid));competitors.push({title:String(i.name??""),url:`https://shopee.com.br/product/${i.shopid}/${i.itemid}`,price:money(i.price_min??i.price),shopId:Number(i.shopid),itemId:Number(i.itemid),...d})}const prices=competitors.map(x=>x.price).filter((v):v is number=>v!=null).sort((a,b)=>a-b);const median=prices.length?(prices.length%2?prices[(prices.length-1)/2]:(prices[prices.length/2-1]+prices[prices.length/2])/2):null;const categories=competitors.filter(x=>x.category).reduce((m,x)=>{const k=`${x.categoryId??""}|${x.category}`;m.set(k,(m.get(k)??0)+1);return m},new Map<string,number>());const categoryEntry=[...categories.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0];const [categoryId,category]=categoryEntry?categoryEntry.split("|",2):[null,null];const attrVotes=new Map<string,Map<string,number>>();for(const c of competitors)for(const[k,v]of Object.entries(c.attributes)){if(!attrVotes.has(k))attrVotes.set(k,new Map());const vm=attrVotes.get(k)!;vm.set(v,(vm.get(v)??0)+1)}const attributes:Record<string,string>={};for(const[k,vm]of attrVotes){const best=[...vm.entries()].sort((a,b)=>b[1]-a[1])[0];if(best&&best[1]>=2)attributes[k]=best[0]}return{competitors,priceMin:prices[0]??null,priceMedian:median,priceMax:prices[prices.length-1]??null,category:category||null,categoryId:categoryId||null,attributes,searchTerms,source:"shopee_public_search"}}catch{return null}}
