"use client";

import { useState } from "react";
import { uploadProductMedia } from "./actions";
const MAX_BYTES = 1_950_000; const MIN_SIDE = 1024; const MAX_FILES = 5;
async function loadImage(file: File) { const url=URL.createObjectURL(file); const image=new Image(); image.src=url; await image.decode(); URL.revokeObjectURL(url); return image; }
function canvasBlob(canvas: HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error("Não foi possível processar a imagem.")),type,quality));}
async function compressImage(file:File){const image=await loadImage(file);let width=image.naturalWidth,height=image.naturalHeight; if(file.size<MAX_BYTES) return {file,width,height}; let quality=.9;const outputType=file.type==="image/png"?"image/webp":file.type==="image/webp"?"image/webp":"image/jpeg";let blob:Blob=file;for(let attempt=0;attempt<10;attempt++){const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));const context=canvas.getContext("2d");if(!context)throw new Error("Seu navegador não conseguiu preparar a imagem.");context.drawImage(image,0,0,canvas.width,canvas.height);blob=await canvasBlob(canvas,outputType,quality);if(blob.size<MAX_BYTES)break;quality=Math.max(.58,quality-.08);if(quality<=.66){const nextWidth=Math.round(width*.88),nextHeight=Math.round(height*.88);if(Math.min(nextWidth,nextHeight)>=MIN_SIDE){width=nextWidth;height=nextHeight;quality=.82;}}}if(blob.size>=2_000_000)throw new Error("Não foi possível reduzir uma das imagens para menos de 2 MB sem comprometer demais a resolução.");const extension=outputType==="image/webp"?"webp":"jpg",base=file.name.replace(/\.[^.]+$/," ").trim()||"produto";return {file:new File([blob],`${base}.${extension}`,{type:outputType,lastModified:Date.now()}),width:Math.round(width),height:Math.round(height)};}
export function MediaUpload({productId}:{productId:string}){const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,input=form.elements.namedItem("file") as HTMLInputElement,files=Array.from(input.files??[]);if(!files.length)return;if(files.length>MAX_FILES){setStatus("Selecione no máximo 5 imagens por vez.");return;}if(files.some(f=>!f.type.startsWith("image/"))){setStatus("Nesta etapa envie somente imagens JPG, PNG ou WebP.");return;}setBusy(true);try{for(let i=0;i<files.length;i++){const original=files[i];setStatus(`Otimizando imagem ${i+1} de ${files.length}…`);const prepared=await compressImage(original);const data=new FormData();data.set("file",prepared.file);data.set("width",String(prepared.width));data.set("height",String(prepared.height));await uploadProductMedia(productId,data);}form.reset();setStatus(`${files.length} imagem(ns) adicionada(s) e otimizada(s) com sucesso.`);}catch(error){setStatus(error instanceof Error?error.message:"Falha ao preparar as imagens.");}finally{setBusy(false);}}return <form onSubmit={submit} className="mediaUpload" encType="multipart/form-data"><input name="file" type="file" accept="image/jpeg,image/png,image/webp" multiple required disabled={busy}/><button className="button primary" type="submit" disabled={busy}>{busy?"Processando…":"Adicionar imagens"}</button><small>Selecione até 5 imagens de uma única vez. Arquivos acima de 1,95 MB são compactados antes do envio.</small>{status&&<small className="mediaStatus">{status}</small>}</form>;}
