"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createProductDraft } from "./actions";
import { uploadProductMedia } from "@/app/products/[id]/media/actions";

const MAX_FILES=5, MAX_BYTES=1_950_000, MIN_SIDE=1024;
async function loadImage(file:File){const url=URL.createObjectURL(file);const image=new Image();image.src=url;await image.decode();URL.revokeObjectURL(url);return image;}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Não foi possível processar a imagem.")),type,quality));}
async function compressImage(file:File){const image=await loadImage(file);let width=image.naturalWidth,height=image.naturalHeight;if(file.size<MAX_BYTES)return{file,width,height};let quality=.9;const outputType=file.type==="image/png"?"image/webp":file.type==="image/webp"?"image/webp":"image/jpeg";let blob:Blob=file;for(let attempt=0;attempt<10;attempt++){const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));const context=canvas.getContext("2d");if(!context)throw new Error("Seu navegador não conseguiu preparar a imagem.");context.drawImage(image,0,0,canvas.width,canvas.height);blob=await canvasBlob(canvas,outputType,quality);if(blob.size<MAX_BYTES)break;quality=Math.max(.58,quality-.08);if(quality<=.66){const nw=Math.round(width*.88),nh=Math.round(height*.88);if(Math.min(nw,nh)>=MIN_SIDE){width=nw;height=nh;quality=.82;}}}if(blob.size>=2_000_000)throw new Error("Não foi possível reduzir uma das imagens para menos de 2 MB.");const ext=outputType==="image/webp"?"webp":"jpg",base=file.name.replace(/\.[^.]+$/," ").trim()||"produto";return{file:new File([blob],`${base}.${ext}`,{type:outputType,lastModified:Date.now()}),width:Math.round(width),height:Math.round(height)};}

export function NewProductForm(){const router=useRouter();const[files,setFiles]=useState<File[]>([]);const[previews,setPreviews]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[status,setStatus]=useState("");
 useEffect(()=>{const urls=files.map(file=>URL.createObjectURL(file));setPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url));},[files]);
 function choose(e:React.ChangeEvent<HTMLInputElement>){const selected=Array.from(e.target.files??[]);if(selected.length>MAX_FILES){setStatus("Selecione no máximo 5 imagens.");e.target.value="";return;}if(selected.some(f=>!["image/jpeg","image/png","image/webp"].includes(f.type))){setStatus("Envie somente imagens JPG, PNG ou WebP.");e.target.value="";return;}setFiles(selected);setStatus("");}
 function remove(index:number){setFiles(current=>current.filter((_,i)=>i!==index));}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!files.length){setStatus("Adicione pelo menos uma imagem-fonte do produto antes de gerar o anúncio.");return;}setBusy(true);setStatus("Criando produto…");try{const data=new FormData(e.currentTarget);data.delete("images");const result=await createProductDraft(data);if(!result.id)throw new Error(result.error||"Não foi possível criar o produto.");for(let i=0;i<files.length;i++){setStatus(`Otimizando e enviando imagem ${i+1} de ${files.length}…`);const prepared=await compressImage(files[i]);const media=new FormData();media.set("file",prepared.file);media.set("width",String(prepared.width));media.set("height",String(prepared.height));await uploadProductMedia(result.id,media);}setStatus("Imagens-fonte adicionadas. Gerando prévia…");router.push(`/products/${result.id}/review?generate=1`);}catch(error){setStatus(error instanceof Error?error.message:"Falha ao gerar anúncio.");setBusy(false);}}
 return <form onSubmit={submit} className="studioForm">
  <section className="formSection"><h2>1. Identificação</h2><p className="note">Copie os dados confirmados do fornecedor. O link é opcional e serve como referência; áreas que exigem login não são lidas automaticamente.</p><div className="formGrid"><label className="wide">Nome do produto<input name="name" required /></label><label>Fornecedor<input name="supplier" /></label><label>SKU<input name="sku" /></label><label>EAN<input name="ean" inputMode="numeric" /></label><label>Marca<input name="brand" /></label><label>Modelo<input name="model" /></label><label>Custo (R$)<input name="cost" inputMode="decimal" /></label><label className="wide">Link de referência do fornecedor (opcional)<input name="supplier_url" type="url" placeholder="https://..." /></label></div></section>
  <section className="formSection"><h2>2. Especificações técnicas do produto</h2><div className="formGrid"><label>NCM<input name="ncm" inputMode="numeric" /></label><label>Peso (kg)<input name="product_weight_kg" inputMode="decimal" /></label><label>Altura (cm)<input name="product_height_cm" inputMode="decimal" /></label><label>Largura (cm)<input name="product_width_cm" inputMode="decimal" /></label><label>Comprimento (cm)<input name="product_length_cm" inputMode="decimal" /></label></div></section>
  <section className="formSection"><h2>3. Itens inclusos</h2><label className="wide">O que vem com o produto?<textarea name="items_included" rows={5} placeholder="Cole ou descreva todos os itens informados pelo fornecedor." /></label></section>
  <section className="formSection"><h2>4. Pacote para envio</h2><p className="note">Use aqui as medidas da embalagem de transporte, não as dimensões do produto montado.</p><div className="formGrid"><label>Peso do pacote (kg)<input name="package_weight_kg" inputMode="decimal" /></label><label>Altura (cm)<input name="package_height_cm" inputMode="decimal" /></label><label>Largura (cm)<input name="package_width_cm" inputMode="decimal" /></label><label>Comprimento (cm)<input name="package_length_cm" inputMode="decimal" /></label></div></section>
  <section className="formSection"><h2>5. Descrição do fornecedor</h2><label className="wide">Descrição completa<textarea name="supplier_description" rows={10} placeholder="Cole aqui toda a descrição fornecida pela WeDrop/fornecedor. A IA usará como evidência, sem inventar características." /></label></section>
  <section className="formSection mediaCreateSection"><h2>6. Imagens-fonte do produto</h2><p className="mediaCreateIntro">Adicione até 5 imagens originais do fornecedor em qualquer ordem. Você não precisa escolher capa ou sequência: o Seller IA analisará as fontes e recomendará a melhor estratégia visual para o anúncio. Arquivos grandes serão otimizados automaticamente para menos de 2 MB.</p><div className="mediaCreateGrid"><label className="mediaDropzone"><input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={choose} disabled={busy}/><span className="uploadIcon">↥</span><b>Clique para selecionar imagens</b><small>ou arraste e solte aqui</small><small>PNG, JPG ou WEBP · máx. 5 arquivos</small></label>{Array.from({length:5}).map((_,i)=>files[i]?<div className="imageSlot filled" key={`${files[i].name}-${i}`}><img src={previews[i]} alt={`Imagem-fonte ${i+1}`} /><button type="button" aria-label={`Remover imagem ${i+1}`} onClick={()=>remove(i)}>×</button><small>{`${i+1}. Imagem-fonte`}</small></div>:<div className="imageSlot" key={i}><span>▧</span><small>{`${i+1}. Imagem-fonte`}</small></div>)}</div><div className="mediaCreateFooter"><span>✓ {files.length} de 5 imagens-fonte adicionadas</span><small>O Seller IA definirá capa, ordem recomendada e eventuais imagens complementares com base no produto e na estratégia do anúncio.</small></div>{status&&<div className="mediaStatus">{status}</div>}</section>
  <div className="formActions"><a className="button" href="/">Cancelar</a><button className="button primary" type="submit" disabled={busy}>{busy?"Preparando anúncio…":"Gerar anúncio →"}</button></div>
 </form>;
}
