import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { optimizeShopee } from "./actions";
import { saveMarketEvidence, savePricingScenario } from "./market/actions";
import { deleteProductMedia } from "./media/actions";
import { MediaUpload } from "./media/media-upload";
import { saveShopeeListingData } from "./listing/actions";
import { validateShopeeMediaSet } from "@/lib/marketplaces/shopee/media";
const money=(value:number|null)=>value==null?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);const mb=(value:number)=>`${(value/1024/1024).toFixed(2).replace(".",",")} MB`;const attributesText=(attributes:unknown)=>attributes&&typeof attributes==="object"?Object.entries(attributes as Record<string,unknown>).map(([key,value])=>`${key}: ${String(value)}`).join("\n"):"";
export default async function ProductPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){const{id}=await params;const query=await searchParams;const supabase=await createClient();const{data:claimsData}=await supabase.auth.getClaims();if(!claimsData?.claims?.sub)redirect("/login");const{data:product}=await supabase.from("products").select("*").eq("id",id).single();if(!product)notFound();const[{data:analysis},{data:listing},{data:pricing},{data:assets}]=await Promise.all([supabase.from("market_analyses").select("*").eq("product_id",id).eq("marketplace","shopee").order("analyzed_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("listings").select("*").eq("product_id",id).eq("marketplace","shopee").order("updated_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("pricing_scenarios").select("*").eq("product_id",id).eq("marketplace","shopee").eq("is_recommended",true).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("product_assets").select("*").eq("product_id",id).eq("marketplace","shopee").order("created_at",{ascending:true})]);const optimize=optimizeShopee.bind(null,id),saveMarket=saveMarketEvidence.bind(null,id),savePricing=savePricingScenario.bind(null,id),deleteMedia=deleteProductMedia.bind(null,id),saveListingData=saveShopeeListingData.bind(null,id);const scoreBreakdown=listing?.score_breakdown as any,media=assets??[];const mediaValidation=validateShopeeMediaSet(media.map(asset=>({kind:asset.asset_type as "image"|"video",name:asset.metadata?.name??asset.storage_path,sizeBytes:asset.metadata?.size_bytes??null,width:asset.metadata?.width??null,height:asset.metadata?.height??null})));
return <main className="studioPage"><div className="crumbs"><a href={`/products/${id}/review`}>Prévia inteligente</a><span>/</span><span>Revisar evidências e simular</span></div>{query.error&&<div className="authAlert error">{query.error}</div>}<div className="studioHeader"><div><div className="eyebrow">Ajustes avançados · Shopee</div><h1>{product.name}</h1><p>Use esta tela para confirmar evidências ou brincar com cenários. O fluxo principal continua na Prévia Inteligente.</p></div><div className="scoreBadge"><span>Score WJR</span><strong>{listing?.listing_score??product.wjr_score??"—"}</strong><small>de 0 a 100</small></div></div>
<div className="workspaceGrid"><section className="formSection"><div className="eyebrow">Evidências de mercado</div><h2>Concorrentes comparáveis</h2>{analysis&&<div className="facts"><div><span>Mínimo</span><b>{money(analysis.price_min)}</b></div><div><span>Mediana</span><b>{money(analysis.price_median)}</b></div><div><span>Máximo</span><b>{money(analysis.price_max)}</b></div><div><span>Amostra</span><b>{Array.isArray(analysis.competitors)?analysis.competitors.length:0}</b></div></div>}<form action={saveMarket} className="evidenceForm"><p className="note">Entrada manual de apoio enquanto o motor de pesquisa automática não estiver integrado. Esses dados nunca são inventados.</p>{[1,2,3].map(n=><div className="evidenceRow" key={n}><input name={`competitor_${n}_title`} placeholder={`Concorrente ${n} · título`}/><input name={`competitor_${n}_url`} placeholder="Link do anúncio"/><input name={`competitor_${n}_price`} inputMode="decimal" placeholder="Preço R$"/></div>)}<button className="button" type="submit">Registrar evidências</button></form></section>
<section className="formSection"><div className="eyebrow">Simulador comercial</div><h2>Preço, taxas, lucro e margem</h2>{pricing&&<div className="facts"><div><span>Preço atual</span><b>{money(pricing.sale_price)}</b></div><div><span>Taxas marketplace</span><b>{money(pricing.marketplace_fee)}</b></div><div><span>Lucro</span><b>{money(pricing.profit)}</b></div><div><span>Margem</span><b>{Number(pricing.margin_pct).toFixed(1)}%</b></div></div>}<form action={savePricing} className="pricingForm"><label>Preço de venda (opcional)<input name="sale_price" inputMode="decimal" placeholder="Vazio = sugerir pela faixa"/></label><label>Margem desejada (%)<input name="target_margin_pct" inputMode="decimal" defaultValue="20"/></label><label>Comissão (%)<input name="marketplace_fee_pct" inputMode="decimal" placeholder="Taxa configurada"/></label><label>Taxa fixa (R$)<input name="fixed_fee" inputMode="decimal" placeholder="0,00"/></label><label>Impostos (%)<input name="taxes_pct" inputMode="decimal" placeholder="0"/></label><label>Outros custos (R$)<input name="other_costs" inputMode="decimal" placeholder="0,00"/></label><button className="button primary" type="submit">Calcular cenário</button></form><p className="note">Nenhuma comissão ou tarifa é assumida como atual sem configuração/validação. Se o preço ficar vazio, o sistema usa a faixa de mercado registrada e respeita o piso necessário para a margem desejada.</p></section></div>
<section className="formSection listingDataPanel"><div className="eyebrow">Confirmação excepcional</div><h2>Categoria e atributos</h2><form action={saveListingData} className="listingDataForm"><label>Categoria recomendada/confirmada<input name="category" defaultValue={listing?.category??""} placeholder="Seller IA deve sugerir"/></label><label>ID da categoria confirmado<input name="marketplace_category_id" defaultValue={listing?.marketplace_category_id??""} placeholder="Pode ficar vazio"/></label><label className="wide">Atributos confirmados<textarea name="attributes" defaultValue={attributesText(listing?.attributes)} placeholder={'Marca: ...\nMaterial: ...\nIdade recomendada: ...'}/></label><button className="button" type="submit">Confirmar ajustes</button></form><p className="note">Esta edição é uma exceção para correção/validação. Categoria e atributos devem ser sugeridos pelo Seller IA.</p></section>
<section className="formSection mediaPanel"><div className="eyebrow">Mídia-fonte</div><h2>Imagens e vídeo</h2><MediaUpload productId={id}/>{media.length>0&&<div className="mediaList">{media.map(asset=><div className="mediaItem" key={asset.id}><div><b>{asset.asset_type==="image"?"Imagem":"Vídeo"} · {asset.metadata?.name??"arquivo"}</b><span>{asset.metadata?.size_bytes?mb(Number(asset.metadata.size_bytes)):"tamanho não informado"}</span></div><form action={deleteMedia}><input type="hidden" name="asset_id" value={asset.id}/><button className="copyButton" type="submit">Remover</button></form></div>)}</div>}{mediaValidation.blockers.length>0&&<div className="pendingBox">{mediaValidation.blockers.map(item=><p key={item}>• {item}</p>)}</div>}</section>
<section className="formSection conversionPanel"><div className="eyebrow">Copy</div><h2>Recalcular com evidências confirmadas</h2>{listing&&<div className="previewBlock"><span>Título</span><h3>{listing.title}</h3><pre>{listing.description}</pre></div>}{scoreBreakdown?.blockers?.length>0&&<div className="pendingBox">{scoreBreakdown.blockers.map((item:string)=><p key={item}>• {item}</p>)}</div>}<div className="formActions"><form action={optimize}><button className="button" type="submit">Recalcular anúncio</button></form><a className="button primary" href={`/products/${id}/review`}>Voltar à Prévia Inteligente →</a></div></section></main>}
