import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { buildShopeeFinalPackage } from "@/lib/marketplaces/shopee/package";
import { CopyButton } from "./copy-button";
import { logout } from "@/app/actions";
const display = (value: any) => typeof value === "number" ? String(value).replace(".", ",") : String(value ?? "PENDENTE");
export default async function FinalPackagePage({ params }: { params: Promise<{ id: string }> }) {
 const { id }=await params; const supabase=await createClient(); const {data:claimsData}=await supabase.auth.getClaims(); if(!claimsData?.claims?.sub) redirect("/login");
 const {data:product}=await supabase.from("products").select("*").eq("id",id).single(); if(!product) notFound();
 const {data:listing}=await supabase.from("listings").select("*").eq("product_id",id).eq("marketplace","shopee").order("updated_at",{ascending:false}).limit(1).maybeSingle(); if(!listing) redirect(`/products/${id}/review?error=${encodeURIComponent("Gere a otimização antes do pacote final")}`);
 const [{data:analysis},{data:pricing},{data:assets}]=await Promise.all([supabase.from("market_analyses").select("*").eq("product_id",id).eq("marketplace","shopee").order("analyzed_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("pricing_scenarios").select("*").eq("product_id",id).eq("marketplace","shopee").eq("is_recommended",true).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("product_assets").select("*").eq("product_id",id).eq("marketplace","shopee").order("created_at",{ascending:true})]);
 const pack=buildShopeeFinalPackage(product,listing,analysis,pricing,assets??[]); const completePackage=pack.fields.map((item)=>`[${item.section}] ${item.label} — ${item.status}:\n${display(item.value)}`).join("\n\n");
 return <div className="shell"><aside className="sidebar"><div className="brand">WJR <span>Seller IA</span></div><nav className="nav"><a href="/">Visão geral</a><a className="active" href="/studio/new">Seller Studio</a><a href="/products">Meus Produtos</a></nav><form action={logout} className="sidebarLogout"><button className="button" type="submit">Sair</button></form></aside><main className="main studioPage">
  <div className="crumbs"><a href={`/products/${id}/review`}>Prévia do anúncio</a><span>/</span><span>Pacote Final Shopee</span></div><div className="studioHeader"><div><div className="eyebrow">Publicação manual · Shopee</div><h1>Pacote Final para cadastrar na Shopee</h1><p>Informações organizadas para copiar e preencher o anúncio. Cada campo mostra se é confirmado, sugestão comercial ou depende de validação.</p></div><div className="scoreBadge"><span>Prontidão</span><strong>{pack.ready?"100%":"—"}</strong><small>{pack.ready?"pronto para revisão":`${pack.pending.length} pendência(s)`}</small></div></div>
  <section className="formSection packageSection"><div className="sectionTitle"><div><div className="eyebrow">Ordem de cadastro</div><h2>Dados do anúncio</h2></div><div className="packageActions"><span className={`statusChip ${pack.ready?"done":""}`}>{pack.ready?"Pronto":"Em preparação"}</span><CopyButton value={completePackage} label="Copiar pacote completo" /></div></div><div className="packageFields">{pack.fields.map((item)=>{const text=display(item.value);return <div className="packageField" key={`${item.section}-${item.label}`}><div className="packageFieldHead"><span>{item.section} · {item.label}</span><CopyButton value={text}/></div><small className="note">{item.status}</small><div>{text}</div></div>})}</div></section>
  <div className="workspaceGrid"><section className="formSection"><div className="eyebrow">Mídia</div><h2>Imagens e vídeo</h2><div className="facts"><div><span>Imagens</span><b>{pack.media.images.length}</b></div><div><span>Vídeos</span><b>{pack.media.videos.length}</b></div></div><p className="note">Imagens devem estar adequadas ao marketplace e abaixo de 2 MB. Vídeo é recomendado quando demonstrar uso real, mas não bloqueia o pacote.</p></section><section className="formSection"><div className="eyebrow">Revisão final</div><h2>Pendências</h2>{pack.pending.length?<div className="pendingBox">{pack.pending.map((item)=><p key={item}>• {item}</p>)}</div>:<p className="note">Nenhuma pendência estrutural detectada. Faça a revisão humana final antes de publicar.</p>}{pack.recommendations.length>0&&<div className="pendingBox"><b>Recomendações que não bloqueiam</b>{pack.recommendations.map((item)=><p key={item}>• {item}</p>)}</div>}</section></div>
  <div className="formActions"><a className="button" href={`/products/${id}/review`}>← Voltar à prévia</a><a className="button" href={`/products/${id}/readiness`}>Ver diagnóstico completo</a></div>
 </main></div>;
}
